pipeline {
  agent {
    label 'jenkins-slave'
  }
  environment {
    project = "gateway"
    imageTag = "${IMAGE_TAG}"
  }
  stages {
    stage('Clean WS') {
      steps {
        deleteDir()
      }
    }
    stage('Git checkout') {
      steps {
        checkout scm
      }
    }

    stage ('Npm Install') {
      steps {
        script {
          sh "npm install"
          currentBuild.setDisplayName("${project}-v${imageTag}" )
        }
      }
    }

    stage('Nx Build') {
      steps {
        script {
          sh "nx build ${project} --configuration=production"
        }
      }
    }

    stage('Docker Build') {
      when {
        anyOf {
          branch 'develop'
          branch 'master'
        }
      }
      steps {
        script {
          docker.withRegistry("https://613765377812.dkr.ecr.us-east-1.amazonaws.com", "ecr:us-east-1:storyfile-ecr-aws") {
            sh("docker build --no-cache -t 613765377812.dkr.ecr.us-east-1.amazonaws.com/storyfile/${project}:${imageTag}  --build-arg APP=${project} .")
            sh("docker push 613765377812.dkr.ecr.us-east-1.amazonaws.com/storyfile/${project}:${imageTag}")
          }
        }
        withCredentials([usernamePassword(credentialsId: 'acrcredentials', passwordVariable: 'AZURE_REGISTRY_PASSWORD', usernameVariable: 'AZURE_REGISTRY_USERNAME')]) {
          script {
            sh("az acr login -n storyfile -u $AZURE_REGISTRY_USERNAME -p $AZURE_REGISTRY_PASSWORD")
            sh("docker tag 613765377812.dkr.ecr.us-east-1.amazonaws.com/storyfile/${project}:${imageTag} storyfile.azurecr.io/storyfile/${project}:${imageTag} ")
            sh("docker push storyfile.azurecr.io/storyfile/${project}:${imageTag}")
          }
        }
      }
    }
    stage('Tag Repository') {
      when {
        branch 'develop'
      }
      steps {
        withCredentials([usernamePassword(credentialsId: 'github-app-storyfile',
          usernameVariable: 'GITHUB_APP',
          passwordVariable: 'GITHUB_ACCESS_TOKEN')]) {
          script {
            sh 'git config --global url."https://x-oauth-basic:${GITHUB_ACCESS_TOKEN}@github.com/Storyfilellc/storyfile-platform.git".insteadof https://github.com/Storyfilellc/storyfile-platform.git'
            sh "git tag ${project}-${imageTag}"
            sh "git push origin ${project}-${imageTag}"
          }
        }
      }
    }
  }
}
